name: unimeet_test
description: A new Flutter project.



publish_to: 'none' 











version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"







dependencies:
  flutter:
    sdk: flutter


  
  
  cupertino_icons: ^1.0.2
  firebase_core:
  cloud_firestore:
  firebase_auth: 
  curved_navigation_bar: ^1.0.3
  email_auth: ^1.0.0
  pinput: ^2.2.12
  page_transition: ^2.0.9
  easy_dialog: ^1.1.0
  image_picker: ^0.8.5+3
  uuid: ^3.0.6
  firebase_storage: ^10.3.7
  path_provider: ^2.0.11
  image_cropper: ^3.0.0
  ntp: ^2.0.0
  cached_network_image: ^3.2.2
  youtube_player_flutter: ^8.1.1
  font_awesome_flutter: ^10.2.1
  video_player: ^2.4.8
  firebase_messaging:
  flutter_local_notifications: ^13.0.0
  timezone: ^0.9.0
  file_picker: ^5.2.4
  flutter_downloader: ^1.9.1
  permission_handler: ^10.2.0
  dio: ^4.0.6
  http:
  flutter_launcher_icons: ^0.11.0
flutter_icons:
  android: true
  ios: true
  image_path: "Images/appLogo-2.png"

  







dev_dependencies:
  flutter_test:
    sdk: flutter

  
  
  
  
  
  flutter_lints: ^2.0.0





flutter:
  fonts:
    - family: Bebas Neue
      fonts:
        - asset: fonts/BebasNeue-Regular.ttf
    - family: rolex
      fonts:
        - asset: fonts/rolex.ttf
    - family: Urbanist
      fonts:
        - asset: fonts/Urbanist-Regular.ttf        
  
  
  
  uses-material-design: true
  assets:
    - Images/
  
  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
